### ISSUE TITLE
[Bug] Useless WGS-level GC bias metric added to TGA

### ISSUE THREAD

**Issue by mathiasbio** [Clinical-Genomics/BALSAMIC#1520]
### Description

In the TGA workflow we're running Sentieon GC bias metrics for the TGA workflow as well, this likely does not add any benefit to the QC analysis and just adds confusion. We should probably just remove this! Especially at least from the deliverables yaml.

Example from @eliottBo :

```
 id: ACC12345
  input: tumor.ACC16605A4.gc_bias_summary.txt
  name: GC_DROPOUT
  step: multiqc_picard_gcbias
  value: 0.0
  condition:
    norm: lt
    threshold: 1.0

 id: ACC12345
  input: tumor.ACC16605A4.hsmetric.txt
  name: GC_DROPOUT
  step: multiqc_picard_HsMetrics
  value: 2.645176
  condition:
    norm: lt
    threshold: 1.0
```

### Pipeline version

16.0.0
